import mods.dropt.Dropt;
//2021.06.27
//Origin_s
//掉落

//原木

Dropt.list("list_wood")
.priority(1)
  .add(Dropt.rule()
      .matchBlocks(["moreplanets:nibiru_log:*", "twilightforest:twilight_log:*", "minecraft:log2:*", "minecraft:log:*"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "axe;0;-1")
      )
      .addDrop(Dropt.drop())
  );
  
//泥土

Dropt.list("list_dirt")
.priority(1)
  .add(Dropt.rule()
      .matchBlocks(["minecraft:dirt:*", "moreplanets:nibiru_grass_path", "minecraft:grass_path", "minecraft:mycelium"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shovel;0;-1")
      )
      .addDrop(Dropt.drop())
	) 
   .add(Dropt.rule()
       .matchBlocks(["minecraft:dirt:*", "moreplanets:nibiru_grass_path", "minecraft:grass_path", "minecraft:mycelium"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:4>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:4>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:dirt:*", "moreplanets:nibiru_grass_path", "minecraft:grass_path", "minecraft:mycelium"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:4>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<minecraft:dirt>], Dropt.range(1))
      )
		
	);

  
//沙子

Dropt.list("list_sand")
.priority(1)
  .add(Dropt.rule()
      .matchBlocks(["minecraft:sand:*"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shovel;0;-1")
      )
      .addDrop(Dropt.drop())
	)	
   .add(Dropt.rule()
       .matchBlocks(["minecraft:sand:*"])
	   .matchDrops([<minecraft:sand>])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:5>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:5>], Dropt.range(4))
       )
    )
	   .add(Dropt.rule()
       .matchBlocks(["minecraft:sand:*"])
	   .matchDrops([<minecraft:sand:1>])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:9>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:9>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:sand:*"])
	   .matchDrops([<minecraft:sand:1>])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:9>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<minecraft:sand:1>], Dropt.range(1))
        )
    )		
   .add(Dropt.rule()
       .matchBlocks(["minecraft:sand:*"])
	   .matchDrops([<minecraft:sand>])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(15))
		    .items([<pyrotech:rock:5>], Dropt.range(4))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<minecraft:sand>], Dropt.range(1))
       )
    );

//沙砾
 
Dropt.list("list_gravel")
.priority(1)
        .add(Dropt.rule()
        .matchBlocks(["minecraft:gravel"])
        .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shovel;0;-1")
        )
        .addDrop(Dropt.drop())
        )
        .add(Dropt.rule()
        .matchBlocks(["minecraft:gravel"])
        .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;1;2;3")
        )
        .addDrop(Dropt.drop()
		    .selector(Dropt.weight(25))
            .items([<pyrotech:rock>], Dropt.range(3))
	    )
        .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:2>], Dropt.range(3))
        )
		.addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:3>], Dropt.range(3))
        )
		.addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:8>], Dropt.range(3))
        )
    )
	
	.add(Dropt.rule()
        .matchBlocks(["minecraft:gravel"])
        .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
        .addDrop(Dropt.drop()
		   .selector(Dropt.weight(20))
		   .items([<minecraft:flint>], Dropt.range(1))  
		)
		.addDrop(Dropt.drop()
           .selector(Dropt.weight(80))
           .items([<minecraft:gravel>], Dropt.range(1))
      )
		
	);

//草方块

Dropt.list("list_grass")
    .priority(1)
    .add(Dropt.rule()
        .matchBlocks(["minecraft:grass", "minecraft:grass_path:1"])
        .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;-1")
        ) 
        .addDrop(Dropt.drop())
	)
   .add(Dropt.rule()
        .matchBlocks(["minecraft:grass"])
        .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
        )
        .addDrop(Dropt.drop()
	        .force()
            .items([<pyrotech:rock:4>], Dropt.range(3))
	    )
		.addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:4>])
        )
        .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:strange_tuber>])
      )
    )
    .add(Dropt.rule()
        .matchBlocks(["minecraft:grass"])
        .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
        .addDrop(Dropt.drop()
		   .selector(Dropt.weight(25))
		   .items([<pyrotech:rock_grass>], Dropt.range(4))  
		)
		.addDrop(Dropt.drop()
           .selector(Dropt.weight(75))
           .items([<pyrotech:rock_grass>], Dropt.range(3))
      )	
	);

//安山岩

Dropt.list("list_andesite")
.priority(1)

   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:5", "pyrotech:cobblestone", "minecraft:stone:6"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:3>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:3>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:5", "pyrotech:cobblestone", "minecraft:stone:6"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:3>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<pyrotech:cobblestone>], Dropt.range(1))
        )	  
    );

//黏土

Dropt.list("list_clay")
.priority(1)
	
   .add(Dropt.rule()
      .matchBlocks(["minecraft:clay"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shovel;0;-1")
       )
       .addDrop(Dropt.drop())
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:clay"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:material:17>], Dropt.range(4))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:material:17>], Dropt.range(5))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:clay"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:material:17>], Dropt.range(5))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<minecraft:clay_ball>], Dropt.range(2))
        )	  
    );

//石头

Dropt.list("list_stone")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone", "minecraft:monster_egg:*", "minecraft:cobblestone"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone", "minecraft:monster_egg:*", "minecraft:cobblestone"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<minecraft:cobblestone>], Dropt.range(1))
        )  
    );

//花岗岩

Dropt.list("list_granite")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:1", "minecraft:stone:2", "pyrotech:cobblestone:2"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:1>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:1>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:1", "minecraft:stone:2", "pyrotech:cobblestone:2"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:1>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<pyrotech:cobblestone:2>], Dropt.range(1))
        )	  
    );
	
//闪长岩

Dropt.list("list_diorite")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:3", "minecraft:stone:4", "pyrotech:cobblestone:1"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:2>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:2>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["minecraft:stone:3", "minecraft:stone:4", "pyrotech:cobblestone:1"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:2>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<pyrotech:cobblestone:1>], Dropt.range(1))
        )	  
    );
	
//煤矿

Dropt.list("list_ore_coal")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["moreplanets:nibiru_ore", "minecraft:coal_ore", "moreplanets:fronos_ore:6"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
	        .force()
		    .items([<pyrotech:rock>], Dropt.range(2))
	   )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(90))
		    .items([<pyrotech:material:21>], Dropt.range(4))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(10))
            .items([<minecraft:coal>], Dropt.range(1))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["moreplanets:nibiru_ore", "minecraft:coal_ore", "moreplanets:fronos_ore:6"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9")
        ) 
	   .addDrop(Dropt.drop()
	        .force()
		    .items([<pyrotech:rock>], Dropt.range(2))
	    )
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(80))
            .items([<minecraft:coal>], Dropt.range(2))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(20))
            .items([<pyrotech:material:21>], Dropt.range(4))
        )
    )
   .add(Dropt.rule()
       .matchBlocks(["moreplanets:nibiru_ore", "minecraft:coal_ore", "moreplanets:fronos_ore:6"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;10;11;12")
        ) 
	   .addDrop(Dropt.drop()
	        .force()
		    .items([<pyrotech:rock>], Dropt.range(2))
	    )
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(90))
            .items([<minecraft:coal>], Dropt.range(6))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(10))
            .items([<pyrotech:material:21>], Dropt.range(4))
        )
    );
	
//化石矿

Dropt.list("list_ore_fossil")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["pyrotech:fossil_ore"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	   )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(90))
		    .items([<pyrotech:material:11>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(10))
            .items([<minecraft:bone>], Dropt.range(2))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["pyrotech:fossil_ore"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10")
        )
	   .addDrop(Dropt.drop()
	        .force()
		    .items([
			<pyrotech:rock>,
			<pyrotech:material:11>
			], Dropt.range(2))
	    )
       .addDrop(Dropt.drop()
	        .selector(Dropt.weight(20))
            .items([<pyrotech:material:11>], Dropt.range(3))
		)
	   .addDrop(Dropt.drop()
	   	    .selector(Dropt.weight(80))
            .items([<minecraft:dye:20>], Dropt.range(2))
        )
    );

//羊毛

Dropt.list("list_wool")
.priority(1)
  .add(Dropt.rule()
      .matchBlocks(["minecraft:wool:*"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shears;0;-1")
      )
      .addDrop(Dropt.drop())
	)
   .add(Dropt.rule()
       .matchBlocks(["minecraft:wool:*"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shears;1;2;3;4;5;6;7;8;9;10;10")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<minecraft:string>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<minecraft:string>], Dropt.range(4))
       )
    );

	
//矿物

//铜矿
Dropt.list("list_orecopper")
    .add(Dropt.rule()
      .matchBlocks(["galacticraftcore:basic_block_core:5", "galacticraftcore:basic_block_moon", "galacticraftplanets:mars", "galacticraftplanets:venus:7", "immersiveengineering:ore", "mekanism:oreblock:1", "moreplanets:diona_block:7", "moreplanets:koentus_block:7", "moreplanets:chalos_block:7", "moreplanets:fronos_ore:3", "moreplanets:nibiru_ore:8"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_copper>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_copper>], Dropt.range(4))  
	  )
  );
  
//铁矿

Dropt.list("list_oreiron")
    .add(Dropt.rule()
      .matchBlocks(["moreplanets:fronos_ore", "moreplanets:nibiru_ore:1", "moreplanets:chalos_block:5", "moreplanets:koentus_block:9", "galacticraftplanets:asteroids_block:5", "galacticraftplanets:mars:3", "minecraft:iron_ore"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_iron>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_iron>], Dropt.range(4))  
	  )
  );
  
//锡矿

Dropt.list("list_oretin")
    .add(Dropt.rule()
      .matchBlocks(["moreplanets:fronos_ore:2", "moreplanets:nibiru_ore:9", "moreplanets:chalos_block:6", "moreplanets:koentus_block:6", "moreplanets:diona_block:6", "mekanism:oreblock:2", "galacticraftplanets:venus:11", "galacticraftplanets:mars:1", "galacticraftcore:basic_block_moon:1", "galacticraftcore:basic_block_core:6"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_tin>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_tin>], Dropt.range(4))  
	  ) 
  );
  
//金矿

Dropt.list("list_oregold")
    .add(Dropt.rule()
      .matchBlocks(["moreplanets:fronos_ore:1", "moreplanets:nibiru_ore:2", "minecraft:gold_ore"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_gold>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_gold>], Dropt.range(4))  
	  ) 
  );

//铝矿

Dropt.list("list_orealuminum")
    .add(Dropt.rule()
      .matchBlocks(["moreplanets:fronos_ore:4", "moreplanets:nibiru_ore:7", "moreplanets:chalos_block:8", "moreplanets:koentus_block:8", "moreplanets:diona_block:8", "galacticraftplanets:venus:6", "galacticraftplanets:asteroids_block:3", "galacticraftcore:basic_block_core:7"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_aluminum>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_aluminum>], Dropt.range(4))  
	  ) 
  );

//锇矿

Dropt.list("list_oreosmium")
    .add(Dropt.rule()
      .matchBlocks(["mekanism:oreblock"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_osmium>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_osmium>], Dropt.range(4))  
	  ) 
  );

//银矿

Dropt.list("list_oresilver")
    .add(Dropt.rule()
      .matchBlocks(["immersiveengineering:ore:3"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_silver>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_silver>], Dropt.range(4))  
	  ) 
  ); 

//铀矿

Dropt.list("list_oreuranium")
    .add(Dropt.rule()
      .matchBlocks(["immersiveengineering:ore:5"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_uranium>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_uranium>], Dropt.range(4))  
	  ) 
  ); 

//方铅矿石

Dropt.list("list_orelead")
    .add(Dropt.rule()
      .matchBlocks(["immersiveengineering:ore:2", "moreplanets:fronos_ore:5"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_lead>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_lead>], Dropt.range(4))  
	  ) 
  );  
  
//阿迪特矿石

Dropt.list("list_oreardite")
    .add(Dropt.rule()
      .matchBlocks(["tconstruct:ore:1"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_ardite>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_ardite>], Dropt.range(4))  
	  ) 
  );  
  
//钴矿

Dropt.list("list_orecobalt")
    .add(Dropt.rule()
      .matchBlocks(["tconstruct:ore"])
	  .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock>], Dropt.range(2))
	  )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<pyrotech:generated_slag_cobalt>], Dropt.range(3))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<pyrotech:generated_slag_cobalt>], Dropt.range(4))  
	  ) 
  );

//Origin_s
//2021.8.6
//TNT 

Dropt.list("list_tnt")
.priority(1)
      .add(Dropt.rule()
      .matchBlocks(["minecraft:tnt"])
      .matchHarvester(Dropt.harvester()
          .type("PLAYER")
          .mainHand("BLACKLIST", [], "shovel;0;-1;1;2;3;4;5;6;7;8;9;10;10")
      )
      .addDrop(Dropt.drop()
	     .force()
		 .items([<pyrotech:rock:5>], Dropt.range(4))
      )
	  .addDrop(Dropt.drop()
	     .selector(Dropt.weight(75))
	     .items([<minecraft:gunpowder>], Dropt.range(1))
	  )
	  .addDrop(Dropt.drop()
         .selector(Dropt.weight(25))
		 .items([<minecraft:gunpowder>], Dropt.range(2))  
	  )
	);

//石灰岩

Dropt.list("list_limestone")
.priority(1)
	
   .add(Dropt.rule()
       .matchBlocks(["pyrotech:limestone"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;0;1;2;3")
       )
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(75))
		    .items([<pyrotech:rock:8>], Dropt.range(3))
       )
       .addDrop(Dropt.drop()
            .selector(Dropt.weight(25))
            .items([<pyrotech:rock:8>], Dropt.range(4))
       )
    )
   .add(Dropt.rule()
       .matchBlocks(["pyrotech:limestone"])
       .matchHarvester(Dropt.harvester()
            .type("PLAYER")
            .mainHand("BLACKLIST", [], "shovel;4;5;6;7;8;9;10;10")
        ) 
       .addDrop(Dropt.drop()
		    .selector(Dropt.weight(15))
            .items([<pyrotech:rock:8>], Dropt.range(4))
		)
	   .addDrop(Dropt.drop()
            .selector(Dropt.weight(85))
            .items([<pyrotech:cobblestone:3>], Dropt.range(1))
        )	  
    );

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  